apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 3200           # The port exposed by the service
      targetPort: 3200     # The port the application listens on inside the container
      nodePort: 32000      # NodePort in a valid range (30000-32767)
  type: NodePort
